### ISSUE TITLE
Support for generics on node classes

### ISSUE THREAD

**Issue by smarr** [graalvm/truffle#209]
Would it be possible to support generics for node classes?

I have a use case similar to the following minimal example:

```Java
@NodeChild(value = "one", type = FooBar.class)
public abstract class FooBar<T extends Data> extends Node {
  private final T someData;

  protected FooBar(final Data someData) { this.someData = someData; }

  public abstract Object executeGeneric(VirtualFrame frame);

  @Specialization
  public Object test(final Object one) {
    return someData.test;
  }

  static class Data {
    public int test;
  }
}
```

Currently, the DSL does not seem to handle generics at all.

It fails like this:

```JavaStackTrace
javax.annotation.processing.FilerException: Illegal name som.interpreter.FooBar<?>NodeGen
	at com.sun.tools.javac.processing.JavacFiler.checkName(JavacFiler.java:495)
	at com.sun.tools.javac.processing.JavacFiler.checkNameAndExistence(JavacFiler.java:517)
	at com.sun.tools.javac.processing.JavacFiler.createSourceOrClassFile(JavacFiler.java:396)
	at com.sun.tools.javac.processing.JavacFiler.createSourceFile(JavacFiler.java:378)
	at com.oracle.truffle.dsl.processor.CodeWriter.createWriter(CodeWriter.java:48)
	at com.oracle.truffle.dsl.processor.java.transform.AbstractCodeWriter.visitType(AbstractCodeWriter.java:82)
```

**Comment by smarr** [comment]
We worked around this for the moment, and it's not an urgent issue. So, I'll close it for the moment.
