### ISSUE TITLE
Annotation processor crashes when sources classes live in default package

### ISSUE THREAD

**Issue by pniederw** [graalvm/truffle#214]
Not that I recommend the practice, but when removing the package declaration from the code given in https://github.com/graalvm/truffle/issues/213, the annotation processor crashes with:

```
Error:(15, 19) java: Uncaught error in AnnotationProcessor while processing CodeGenError.Types : javax.annotation.processing.FilerException: Illegal name .TypesGen
  java.lang.RuntimeException: javax.annotation.processing.FilerException: Illegal name .TypesGen
  	at com.oracle.truffle.dsl.processor.java.transform.AbstractCodeWriter.visitType(AbstractCodeWriter.java:86)
  	at com.oracle.truffle.dsl.processor.java.transform.AbstractCodeWriter.visitType(AbstractCodeWriter.java:59)
  	at com.oracle.truffle.dsl.processor.java.model.CodeElementScanner.visitType(CodeElementScanner.java:70)
  	at com.oracle.truffle.dsl.processor.java.model.CodeTypeElement.accept(CodeTypeElement.java:202)
  	at com.oracle.truffle.dsl.processor.AnnotationProcessor.process(AnnotationProcessor.java:102)
  	at com.oracle.truffle.dsl.processor.TruffleProcessor.processElement(TruffleProcessor.java:98)
  	at com.oracle.truffle.dsl.processor.TruffleProcessor.processImpl(TruffleProcessor.java:74)
  	at com.oracle.truffle.dsl.processor.TruffleProcessor.process(TruffleProcessor.java:60)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
  	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
  	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:180)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:463)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:319)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:231)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:193)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1282)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:956)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1028)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:915)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:741)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:387)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:195)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:295)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:238)
  	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:44)
  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  	at java.lang.Thread.run(Thread.java:745)
  Caused by: javax.annotation.processing.FilerException: Illegal name .TypesGen
  	at com.sun.tools.javac.processing.JavacFiler.checkName(JavacFiler.java:495)
  	at com.sun.tools.javac.processing.JavacFiler.checkNameAndExistence(JavacFiler.java:517)
  	at com.sun.tools.javac.processing.JavacFiler.createSourceOrClassFile(JavacFiler.java:396)
  	at com.sun.tools.javac.processing.JavacFiler.createSourceFile(JavacFiler.java:378)
  	at com.oracle.truffle.dsl.processor.CodeWriter.createWriter(CodeWriter.java:48)
  	at com.oracle.truffle.dsl.processor.java.transform.AbstractCodeWriter.visitType(AbstractCodeWriter.java:82)
  	... 39 more
```

**Comment by chumer** [comment]
Fixed in:
https://github.com/graalvm/truffle/commit/bd495788c0395505d113a1e9186ffe65dc551bf8
